# Generated by Django 5.1.4 on 2025-01-28 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_class_image_notice_question_bank_staff_teacher_and_more'),
    ]

   