# Generated by Django 5.1.4 on 2025-01-28 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_class_image_notice_question_bank_staff_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Picture/mom/')),
                ('year', models.IntegerField(default='2024')),
            ],
        ),
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=10)),
                ('msg', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Question_Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=100)),
                ('option_a', models.CharField(max_length=45)),
                ('option_b', models.CharField(max_length=45)),
                ('option_c', models.CharField(max_length=45)),
                ('option_d', models.CharField(max_length=45)),
                ('correct_option', models.CharField(max_length=45)),
                ('per_question_marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mob', models.CharField(max_length=10)),
                ('bod', models.DateField(auto_now=True)),
                ('gender', models.CharField(default='', max_length=10)),
                ('add', models.TextField(default='')),
                ('qulification', models.CharField(default='', max_length=10)),
                ('specialization', models.CharField(default='', max_length=20)),
                ('experience', models.IntegerField()),
                ('state', models.CharField(default='', max_length=10)),
                ('city', models.CharField(default='', max_length=10)),
                ('area', models.CharField(default='', max_length=10)),
                ('code', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mob', models.CharField(max_length=10)),
                ('bod', models.DateField(auto_now=True)),
                ('gender', models.CharField(default='', max_length=10)),
                ('add', models.TextField(default='')),
                ('pas', models.CharField(default='', max_length=50)),
                ('qulification', models.CharField(default='', max_length=10)),
                ('specialization', models.CharField(default='', max_length=20)),
                ('experience', models.IntegerField()),
                ('state', models.CharField(default='', max_length=10)),
                ('city', models.CharField(default='', max_length=10)),
                ('area', models.CharField(default='', max_length=10)),
                ('code', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('location_url', models.CharField(max_length=100)),
                ('contact_no', models.BigIntegerField()),
                ('pin_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='education.class')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('batch_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_master', to='education.division')),
            ],
        ),
        migrations.CreateModel(
            name='exam_time_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField(auto_now=True)),
                ('day', models.CharField(max_length=10)),
                ('total_marks', models.IntegerField()),
                ('Class_obj', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='examtimetable', to='education.class')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default='', max_digits=10)),
                ('class_related', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='education.class')),
            ],
        ),
        migrations.CreateModel(
            name='inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mob', models.CharField(max_length=10)),
                ('pmob', models.CharField(max_length=10)),
                ('bod', models.DateField(auto_now=True)),
                ('add', models.TextField(default='')),
                ('pas', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=10)),
                ('state', models.CharField(default='', max_length=10)),
                ('city', models.CharField(default='', max_length=10)),
                ('area', models.CharField(default='', max_length=10)),
                ('code', models.CharField(default='', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('class_obj', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='inquiry', to='education.class')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieve_marks', models.IntegerField()),
                ('exam_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='education.exam_time_table')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mob', models.CharField(max_length=10)),
                ('pmob', models.CharField(max_length=10)),
                ('bod', models.DateField(auto_now=True)),
                ('add', models.TextField(default='')),
                ('pas', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=10)),
                ('class_obj', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='student', to='education.class')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=50)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='education.class')),
            ],
        ),
        migrations.AddField(
            model_name='exam_time_table',
            name='Subjects_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examtimetable', to='education.subjects'),
        ),
        migrations.CreateModel(
            name='batch_time_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True)),
                ('day', models.CharField(max_length=10)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batchtimetable', to='education.class')),
                ('batch_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batchtimetable', to='education.division')),
                ('Subjects_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batchtimetable', to='education.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Study_Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_url', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('sub_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_material', to='education.subjects')),
                ('teacher_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_material', to='education.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_score', models.IntegerField()),
                ('batch_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='education.division')),
                ('sub_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='education.subjects')),
                ('teacher_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='education.teacher')),
            ],
        ),
    ]
