# Generated by Django 5.1.4 on 2025-01-29 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='education.inquiry'),
        ),
    ]
