# Generated by Django 5.1.4 on 2025-01-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_remove_student_student_name_alter_pay_student_name'),
    ]

   