# Generated by Django 5.1.4 on 2025-01-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_student_amount'),
    ]

    
