# Generated by Django 5.1.4 on 2025-01-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_student_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='amount',
            field=models.IntegerField(default=''),
        ),
    ]
