# Generated by Django 5.1.4 on 2025-01-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_pay_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('send', 'send')], default='pending', max_length=10),
        ),
    ]
