# Generated by Django 5.1.4 on 2025-01-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
