# Generated by Django 5.1.4 on 2025-01-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_student_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_time_table',
            name='e_time',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='exam_time_table',
            name='time',
            field=models.IntegerField(default=''),
        ),
    ]
