# Generated by Django 5.1.4 on 2025-01-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0014_exam_time_table_e_time_alter_exam_time_table_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_time_table',
            name='e_time',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='batch_time_table',
            name='time',
            field=models.IntegerField(default=''),
        ),
    ]
