# Generated by Django 5.1.4 on 2025-02-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0016_student_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approve', 'approve')], default='pending', max_length=10),
        ),
    ]
