# Generated by Django 5.1.4 on 2025-02-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_teacher_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approve', 'approve')], default='pending', max_length=10),
        ),
    ]
