# Generated by Django 5.1.4 on 2025-02-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0020_approveteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='pas',
            field=models.CharField(default='', max_length=50),
        ),
    ]
