# Generated by Django 5.1.4 on 2025-02-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0021_staff_pas'),
    ]

    operations = [
        migrations.CreateModel(
            name='approvestaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mob', models.CharField(max_length=10)),
                ('bod', models.DateField(auto_now=True)),
                ('gender', models.CharField(default='', max_length=10)),
                ('add', models.TextField(default='')),
                ('pas', models.CharField(default='', max_length=50)),
                ('qulification', models.CharField(default='', max_length=10)),
                ('specialization', models.CharField(default='', max_length=20)),
                ('experience', models.IntegerField()),
            ],
        ),
    ]
