# Generated by Django 5.1.4 on 2025-02-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0022_approvestaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch_time_table',
            name='e_time',
            field=models.IntegerField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='batch_time_table',
            name='time',
            field=models.IntegerField(default='', unique=True),
        ),
    ]
