# Generated by Django 5.1.4 on 2025-02-04 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0024_alter_batch_time_table_e_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='Image',
        ),
    ]
