# Generated by Django 5.1.4 on 2025-02-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0025_rename_image_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Pictures/mom/')),
                ('year', models.IntegerField(default='2024')),
            ],
        ),
        migrations.DeleteModel(
            name='image',
        ),
    ]
