# Generated by Django 5.1.4 on 2025-02-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0026_gallery_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='Image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
