# Generated by Django 5.1.4 on 2025-02-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0027_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='Image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
