# Generated by Django 5.1.4 on 2025-02-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0028_alter_gallery_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='Image',
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='', upload_to='gallery/'),
        ),
    ]
