# Generated by Django 5.1.4 on 2025-02-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0029_remove_gallery_image_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(default='', upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='study_material',
            name='pdf_url',
            field=models.FileField(upload_to=''),
        ),
    ]
