# Generated by Django 5.1.4 on 2025-02-04 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0031_alter_gallery_image_alter_study_material_pdf_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study_material',
            name='sub_obj',
        ),
        migrations.AlterField(
            model_name='study_material',
            name='teacher_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_material', to='education.approveteacher'),
        ),
    ]
