# Generated by Django 5.1.4 on 2025-02-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0032_remove_study_material_sub_obj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study_material',
            name='pdf_url',
        ),
    ]
