# Generated by Django 5.1.4 on 2025-02-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0033_remove_study_material_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='study_material',
            name='pdf_url',
            field=models.FileField(default='', upload_to='documents/'),
        ),
    ]
