# Generated by Django 5.1.4 on 2025-02-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0034_study_material_pdf_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='Pictures/mom/'),
        ),
    ]
