# Generated by Django 5.1.4 on 2025-02-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0035_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='year',
            field=models.IntegerField(default=''),
        ),
    ]
