# Generated by Django 5.1.4 on 2025-02-05 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0037_alter_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='education.student'),
        ),
    ]
