# Generated by Django 5.1.4 on 2025-02-05 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0038_marks_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='student',
            new_name='student_obj',
        ),
    ]
