# Generated by Django 5.1.4 on 2025-02-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0039_rename_student_marks_student_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch_time_table',
            name='e_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='batch_time_table',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='batch_time_table',
            unique_together={('time', 'e_time', 'day', 'class_obj')},
        ),
    ]
