# Generated by Django 5.1.4 on 2025-02-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0041_alter_batch_time_table_e_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch_time_table',
            name='time',
            field=models.IntegerField(default=''),
        ),
    ]
