# Generated by Django 5.1.4 on 2025-02-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0042_alter_batch_time_table_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch_time_table',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='batch_time_table',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10),
        ),
    ]
