# Generated by Django 5.1.6 on 2025-02-07 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0043_alter_batch_time_table_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study_material',
            name='Class_obj',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sm', to='education.class'),
        ),
    ]
