# Generated by Django 5.1.6 on 2025-02-07 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0044_study_material_class_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study_material',
            name='Class_obj',
        ),
        migrations.AddField(
            model_name='approveteacher',
            name='Class_obj',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ateacher', to='education.class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Class_obj',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='education.class'),
        ),
    ]
