# Generated by Django 5.1.6 on 2025-02-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0047_remove_approveteacher_user_remove_student_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study_material',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
