# Generated by Django 5.1.6 on 2025-02-08 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0050_attendance_class_obj_attendance_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='class_obj',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='staff',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.student'),
        ),
    ]
