# Generated by Django 5.1.6 on 2025-02-09 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0051_remove_attendance_batch_remove_attendance_class_obj_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions_Ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('option1', models.CharField(max_length=255)),
                ('option2', models.CharField(max_length=255)),
                ('option3', models.CharField(max_length=255)),
                ('option4', models.CharField(max_length=255)),
                ('correct_option', models.CharField(max_length=255)),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_marks', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Question_Bank',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='batch_obj',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='date',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='sub_obj',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='teacher_obj',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='total_score',
        ),
        migrations.AddField(
            model_name='quiz',
            name='class_obj',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='education.class'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject_obj',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='education.subjects'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='education.student'),
        ),
        migrations.AddField(
            model_name='questions_ans',
            name='quiz',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='education.quiz'),
        ),
        migrations.AddField(
            model_name='studentquiz',
            name='quiz',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='education.quiz'),
        ),
        migrations.AddField(
            model_name='studentquiz',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
