# Generated by Django 5.1.6 on 2025-02-09 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0052_questions_ans_studentquiz_delete_question_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions_ans',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.class'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='subject_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.subjects'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.approveteacher'),
        ),
        migrations.AlterField(
            model_name='studentquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.quiz'),
        ),
        migrations.AlterField(
            model_name='studentquiz',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.student'),
        ),
    ]
