# Generated by Django 5.1.6 on 2025-02-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0053_alter_questions_ans_quiz_alter_quiz_class_obj_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('teacher', 'title')},
        ),
    ]
