# Generated by Django 5.1.6 on 2025-02-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0054_alter_quiz_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
