# Generated by Django 5.1.6 on 2025-02-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0055_alter_notice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reset_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
