# Generated by Django 5.1.6 on 2025-02-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0056_student_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvestaff',
            name='reset_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='approveteacher',
            name='reset_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
