# Generated by Django 5.1.6 on 2025-02-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0057_approvestaff_reset_token_approveteacher_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='pas',
            field=models.CharField(default='', max_length=15),
        ),
    ]
