# Generated by Django 5.1.6 on 2025-02-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0058_author_pas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch_time_table',
            name='e_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='batch_time_table',
            name='time',
            field=models.TimeField(),
        ),
    ]
