# Generated by Django 5.1.6 on 2025-02-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0059_alter_batch_time_table_e_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_time_table',
            name='e_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='exam_time_table',
            name='time',
            field=models.TimeField(),
        ),
    ]
