# Generated by Django 5.1.6 on 2025-02-23 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0061_city_state_area_city_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='area',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='inquiry', to='education.area'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='inquiry', to='education.city'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='inquiry', to='education.state'),
        ),
    ]
