# Generated by Django 5.1.6 on 2025-02-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0063_remove_staff_area_remove_staff_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='bod',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='bod',
        ),
    ]
