# Generated by Django 5.1.6 on 2025-02-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0064_remove_staff_bod_remove_teacher_bod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approveteacher',
            name='bod',
            field=models.DateField(auto_now_add=True),
        ),
    ]
