# Generated by Django 5.1.6 on 2025-02-24 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0065_alter_approveteacher_bod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Class_obj',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='education.class'),
        ),
    ]
