# Generated by Django 5.1.6 on 2025-03-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0069_alter_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvestaff',
            name='image',
            field=models.ImageField(default='', upload_to='Pictures\\mom\\'),
        ),
        migrations.AddField(
            model_name='approveteacher',
            name='image',
            field=models.ImageField(default='', upload_to='Pictures\\mom\\'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='image',
            field=models.ImageField(default='', upload_to='Pictures\\mom\\'),
        ),
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(default='', upload_to='Pictures\\mom\\'),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='', upload_to='Pictures\\mom\\'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='Pictures\\mom\\'),
        ),
    ]
